// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtxZBmZ9fb1itO6M9iY3LYVXFbpgM2V4',
    appId: '1:329326881797:web:c6ff5a8191af151505006c',
    messagingSenderId: '329326881797',
    projectId: 'diabetes-guide-f8013',
    authDomain: 'diabetes-guide-f8013.firebaseapp.com',
    storageBucket: 'diabetes-guide-f8013.appspot.com',
    measurementId: 'G-7YG9L28QBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkSc4aqRbF1xNKaB5mHfhDA830vyJ5LSs',
    appId: '1:329326881797:android:772ef3552c309a4c05006c',
    messagingSenderId: '329326881797',
    projectId: 'diabetes-guide-f8013',
    storageBucket: 'diabetes-guide-f8013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5Povt61tnGqYfl1fFBH3QoDa0BApyl0',
    appId: '1:329326881797:ios:9effa66a80b7c1bb05006c',
    messagingSenderId: '329326881797',
    projectId: 'diabetes-guide-f8013',
    storageBucket: 'diabetes-guide-f8013.appspot.com',
    iosBundleId: 'com.example.diabetic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD5Povt61tnGqYfl1fFBH3QoDa0BApyl0',
    appId: '1:329326881797:ios:41e784c965ba21d405006c',
    messagingSenderId: '329326881797',
    projectId: 'diabetes-guide-f8013',
    storageBucket: 'diabetes-guide-f8013.appspot.com',
    iosBundleId: 'com.example.diabetic.RunnerTests',
  );
}
